server:
  port: 9080
  address: localhost
  servlet:
    context-path: /cmdb

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:13306/cmdb_os?characterEncoding=utf8&serverTimezone=UTC
    #url: jdbc:mysql://localhost:13306/cmdb_nm?characterEncoding=utf8&serverTimezone=UTC
    #username: root
    #password: 123456
#smoke
    #url: jdbc:mysql://127.0.0.1:3306/fprs?characterEncoding=utf8&serverTimezone=UTC
    #username: fprs
    #password: password
#uat
    url: jdbc:mysql://127.0.0.1:3306/wecube_core_03?characterEncoding=utf8&serverTimezone=UTC
    username: wecube_core_03
    password: password


  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
cmdb:
  datasource:
    schema: fprs

logging:
  level:
    root: INFO
    com:
      webank:
        cmdb: DEBUG

cas-server:
  url: http://127.0.0.1:8080/cas
  enabled: false
  whitelist-ip-address: 127.0.0.1


